### ISSUE TITLE
Fails to compile with libinput 0.7.0

### ISSUE THREAD

**Issue by 5paceToast** [Cloudef/loliwm#58]
too many arguments to function libinput_event_pointer_get_axis_value under gcc (permissive)
udev.c:165

under clang: conflicting types for wl_resource_post_event (wayland-server.h:322)

**Comment by Cloudef** [comment]
You need libinput from git.

**Comment by 5paceToast** [comment]
Works with 0.9.0, which is in Gentoo tree. Thanks!
