### ISSUE TITLE
Fails to build on Ubuntu 14.10

### ISSUE THREAD

**Issue by tpimh** [Cloudef/loliwm#81]
Subj.
```
loliwm/lib/wlc/src/session/udev.c: In function ‘input_event’:
loliwm/lib/wlc/src/session/udev.c:165:38: error: too many arguments to function ‘libinput_event_pointer_get_axis_value’
                ev.scroll.amount[0] = libinput_event_pointer_get_axis_value(pev, LIBINPUT_POINTER_AXIS_SCROLL_VERTICAL);
                                      ^
In file included from loliwm/lib/wlc/src/session/udev.c:15:0:
/usr/include/libinput.h:653:1: note: declared here
 libinput_event_pointer_get_axis_value(struct libinput_event_pointer *event);
 ^
loliwm/lib/wlc/src/session/udev.c:166:38: error: too many arguments to function ‘libinput_event_pointer_get_axis_value’
                ev.scroll.amount[1] = libinput_event_pointer_get_axis_value(pev, LIBINPUT_POINTER_AXIS_SCROLL_HORIZONTAL);
                                      ^
In file included from loliwm/lib/wlc/src/session/udev.c:15:0:
/usr/include/libinput.h:653:1: note: declared here
 libinput_event_pointer_get_axis_value(struct libinput_event_pointer *event);
 ^
loliwm/lib/wlc/src/session/udev.c:169:16: warning: implicit declaration of function ‘libinput_event_pointer_has_axis’ [-Wimplicit-function-declaration]
                if (libinput_event_pointer_has_axis(pev, LIBINPUT_POINTER_AXIS_SCROLL_VERTICAL))
                ^
```

**Comment by Cloudef** [comment]
Your libinput is too old.
